name: Go

on: [push]

env:
  GO_VERSION: '>=1.24.0'

jobs:

  build:
    name: Build
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        # "pg_ctl start" fails on these platforms for unknown reasons.
        #
        # See also: https://github.com/koron-go/pgctl/issues/9
        #
        #- ubuntu-24.04-arm
        #- windows-latest

    steps:

    - uses: actions/checkout@v5

    - uses: actions/setup-go@v6
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Setup PostgreSQL
      uses: tj-actions/install-postgresql@a889ed6c6fa05022333ed4101295bb1d604f97a8 # v3.2.0
      with:
        postgresql-version: 17

    - run: go test ./...

    - name: Build all "main" packages
      shell: bash
      run: |
        go list -f '{{if (eq .Name "main")}}{{.ImportPath}} .{{slice .ImportPath (len .Module.Path)}}{{end}}' ./... | while IFS= read -r line ; do
          read -a e <<< "$line"
          path="${e[0]}"
          dir="${e[1]}"
          name=$(basename $path)
          printf "building %s\t(%s)\n" $name $dir
          ( cd "$dir" && go build )
        done

# based on: github.com/koron-go/_skeleton/.github/workflows/go.yml
# $Hash:9c8a3b994481420b53acfa5fc528096004ca3db524f1d95554dcbad1$
